# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(902, 732)
        self.nom_pere_2 = QtWidgets.QLineEdit(Dialog)
        self.nom_pere_2.setGeometry(QtCore.QRect(20, 590, 161, 20))
        self.nom_pere_2.setObjectName("nom_pere_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 471, 31))
        self.label.setStyleSheet("font-size :  20px;\n"
"border-radius : 8px solid gray;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(160, 500, 231, 31))
        self.label_11.setStyleSheet("font-size :  20px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.photo_label = QtWidgets.QLabel(Dialog)
        self.photo_label.setGeometry(QtCore.QRect(510, 400, 151, 101))
        self.photo_label.setStyleSheet("border : 1px solid  rgb(184, 184, 184);\n"
"border-radius : 10px;")
        self.photo_label.setText("")
        self.photo_label.setPixmap(QtGui.QPixmap(":/newPrefix/assets/image/161085384_4028971917170348_1595544585493431467_n.jpeg"))
        self.photo_label.setScaledContents(False)
        self.photo_label.setObjectName("photo_label")
        self.pays = QtWidgets.QLineEdit(Dialog)
        self.pays.setGeometry(QtCore.QRect(20, 400, 161, 20))
        self.pays.setObjectName("pays")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(420, 280, 161, 20))
        self.label_8.setStyleSheet("font-size :  16px;")
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(380, 560, 161, 20))
        self.label_14.setStyleSheet("font-size :  16px;")
        self.label_14.setObjectName("label_14")
        self.btn_annuler_2 = QtWidgets.QPushButton(Dialog)
        self.btn_annuler_2.setGeometry(QtCore.QRect(390, 650, 101, 31))
        self.btn_annuler_2.setStyleSheet("background-color : red;\n"
"color: white;\n"
"border-radius : 2 px solid red;\n"
"border: none;\n"
"font-size :  20px;\n"
"padding : 3px;\n"
"")
        self.btn_annuler_2.setObjectName("btn_annuler_2")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 560, 161, 20))
        self.label_15.setStyleSheet("font-size :  16px;")
        self.label_15.setObjectName("label_15")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 161, 20))
        self.label_7.setStyleSheet("font-size :  16px;")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 161, 20))
        self.label_5.setStyleSheet("font-size :  16px;")
        self.label_5.setObjectName("label_5")
        self.lieu = QtWidgets.QLineEdit(Dialog)
        self.lieu.setGeometry(QtCore.QRect(390, 260, 161, 20))
        self.lieu.setObjectName("lieu")
        self.lieu_label = QtWidgets.QLabel(Dialog)
        self.lieu_label.setGeometry(QtCore.QRect(390, 230, 161, 20))
        self.lieu_label.setStyleSheet("font-size :  16px;")
        self.lieu_label.setObjectName("lieu_label")
        self.nom = QtWidgets.QLineEdit(Dialog)
        self.nom.setGeometry(QtCore.QRect(20, 190, 161, 20))
        self.nom.setObjectName("nom")
        self.btn_envoi_2 = QtWidgets.QPushButton(Dialog)
        self.btn_envoi_2.setGeometry(QtCore.QRect(140, 650, 101, 31))
        self.btn_envoi_2.setStyleSheet("background-color :  rgb(85, 255, 127);\n"
"color : white;\n"
"border-radius : 15 px solid white;\n"
"border : none;\n"
"font-weigth :bold;\n"
"font-size :  20px;\n"
"")
        self.btn_envoi_2.setObjectName("btn_envoi_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 370, 161, 20))
        self.label_9.setStyleSheet("font-size :  16px;")
        self.label_9.setObjectName("label_9")
        self.prenom = QtWidgets.QLineEdit(Dialog)
        self.prenom.setGeometry(QtCore.QRect(390, 200, 161, 20))
        self.prenom.setObjectName("prenom")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 161, 20))
        self.label_3.setStyleSheet("font-size :  16px;")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 361, 31))
        self.label_2.setStyleSheet("font-size :  20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_photo = QtWidgets.QPushButton(Dialog)
        self.btn_photo.setGeometry(QtCore.QRect(310, 420, 181, 41))
        self.btn_photo.setStyleSheet("font-size : 20px;")
        self.btn_photo.setObjectName("btn_photo")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 170, 161, 20))
        self.label_4.setStyleSheet("font-size :  16px;")
        self.label_4.setObjectName("label_4")
        self.domicile = QtWidgets.QLineEdit(Dialog)
        self.domicile.setGeometry(QtCore.QRect(20, 330, 161, 20))
        self.domicile.setObjectName("domicile")
        self.nom_mere_2 = QtWidgets.QLineEdit(Dialog)
        self.nom_mere_2.setGeometry(QtCore.QRect(380, 590, 161, 20))
        self.nom_mere_2.setObjectName("nom_mere_2")
        self.sexe_h = QtWidgets.QRadioButton(Dialog)
        self.sexe_h.setGeometry(QtCore.QRect(380, 310, 81, 20))
        self.sexe_h.setStyleSheet("font-size :  16px;")
        self.sexe_h.setObjectName("sexe_h")
        self.sexe_f = QtWidgets.QRadioButton(Dialog)
        self.sexe_f.setGeometry(QtCore.QRect(470, 310, 71, 20))
        self.sexe_f.setStyleSheet("font-size :  16px;")
        self.sexe_f.setObjectName("sexe_f")
        self.date = QtWidgets.QDateEdit(Dialog)
        self.date.setGeometry(QtCore.QRect(20, 260, 161, 21))
        self.date.setObjectName("date")
        self.sexe_label = QtWidgets.QLabel(Dialog)
        self.sexe_label.setGeometry(QtCore.QRect(380, 340, 181, 41))
        self.sexe_label.setStyleSheet("border : 1px solid gray;\n"
"font-size : 16px;")
        self.sexe_label.setText("")
        self.sexe_label.setObjectName("sexe_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ENREGISTREMENT"))
        self.label_11.setText(_translate("Dialog", "Informations Parentale"))
        self.label_8.setText(_translate("Dialog", "Genre"))
        self.label_14.setText(_translate("Dialog", "Nom de la Mère"))
        self.btn_annuler_2.setText(_translate("Dialog", "Annuler"))
        self.label_15.setText(_translate("Dialog", "Nom du Père"))
        self.label_7.setText(_translate("Dialog", "Domicile"))
        self.label_5.setText(_translate("Dialog", "Date de naissance"))
        self.lieu_label.setText(_translate("Dialog", "Lieu de Naissance"))
        self.btn_envoi_2.setText(_translate("Dialog", "Envoyer"))
        self.label_9.setText(_translate("Dialog", "Nationnalité"))
        self.label_3.setText(_translate("Dialog", "Entrez votre nom"))
        self.label_2.setText(_translate("Dialog", "Informations Personnelles"))
        self.btn_photo.setText(_translate("Dialog", "Choisir une photo"))
        self.label_4.setText(_translate("Dialog", "Entrez votre prénom"))
        self.sexe_h.setText(_translate("Dialog", "Homme"))
        self.sexe_f.setText(_translate("Dialog", "Femme"))
import images_rc
